accountant/accountant/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views
from users.views import CustomLoginView
from users.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('', include('users.urls')),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

accountant/users/urls.py
from django.urls import path
from .views import home, RegisterView, whoami

app_name = 'users'
urlpatterns = [
    path('', home, name='users-home'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('whoami/', whoami, name='whoami'),
]

accountant/web/urls.py
from django.urls import path
from web import views

app_name = 'web'
urlpatterns = [
    path('submit/expense/', views.submit_expense, name='submit_expense'),
    path('submit/income/', views.submit_income, name='submit_income'),
    path('query/expenses/', views.query_expenses, name='query_expenses'),
    path('query/incomes/', views.query_incomes, name='query_incomes'),
    path('generalstat/', views.generalstat, name='generalstat'),
    path('edit/expense/', views.edit_expense, name='edit_expense'),
    path('edit/income/', views.edit_income, name='edit_income'),
]

accountant/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Token(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=48)

    def __str__(self):
        return "{}-token".format(self.user)
    

accountant/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


from captcha.fields import CaptchaField

class RegisterForm(UserCreationForm):
    # recaptcha
    captcha = CaptchaField()

    # fields we want to include and customize in our form
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'نام',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'نام خانوادگی',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'نام کاربری',
                                                             'class': 'form-control',
                                                             'autofocus': 'false'
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'ایمیل',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'رمز ورود',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'تایید رمز ورود',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    # recaptcha
    captcha = CaptchaField()
    
    # other fields
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',}))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

accountant/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password, check_password

import urllib
from django.conf import settings
import json
from json import JSONEncoder

from django.utils.crypto import get_random_string

from time import gmtime, strftime

from django.http import JsonResponse

from django.contrib.auth import authenticate, login, logout

from .forms import RegisterForm, LoginForm
from .utils import grecaptcha_verify, RateLimited, get_client_ip
from .models import Token

from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

# Creating a token containing 48 charecter

import string, random
char_set = string.ascii_letters + string.digits
create_token = lambda: ''.join(random.sample(char_set, 48))

# Views

from web.models import Expense, Income
def home(request):
    user = request.user

    if user.is_authenticated:
        expenses = Expense.objects.filter(user=user)
        incomes = Income.objects.filter(user=user)
    else:
        expenses = None
        incomes = None
    context = {
        'expenses': expenses,
        'incomes': incomes,
    }
    return render(request, 'users/home.html', context)


class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if User.objects.filter(email=request.POST['email']).exists():
            context = {
                'message': '''متاسفانه این ایمیل قبلا استفاده شده است. در صورتی که این ایمیل شما است،
                             از صفحه ورود گزینه فراموشی پسورد رو انتخاب کنین. ببخشید که فرم ذخیره نشده. درست می شه'''}  # TODO: forgot password
            # TODO: keep the form data
            context['form'] = form
            return render(request, self.template_name, context)
        
        if form.is_valid():
            # if not grecaptcha_verify(request):  # captcha was not correct
            #     message = 'کپچای گوگل درست وارد نشده بود'
            #     messages.error(request, message)

            this_user = form.save()

            this_token = create_token()
            Token.objects.create(user=this_user, token=this_token)

            username = form.cleaned_data.get('username')
            messages.success(request, f'''حساب برای {username} ایجاد شد. توکن شما "{this_token}" است. آن را ذخیره کنید. برای ادامه فرایند لطفا وارد حساب خود شوید:)''')
            return redirect(to='login')

        return render(request, self.template_name, {'form': form})


# Class based view that extends from the built in login view to add a remember me functionality
class CustomLoginView(LoginView):
    form_class = LoginForm
    global form

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)    
    

# return username based on sent POST Token

@csrf_exempt
@require_POST
def whoami(request):
    if 'token' in request.POST:
        this_token = request.POST['token']  # TODO: Check if there is no `token`- done-please Check it
        # Check if there is a user with this token; will retun 404 instead.
        this_user = get_object_or_404(User, token__token=this_token)

        return JsonResponse({
            'user': this_user.username,
        }, encoder=JSONEncoder)  # return {'user':'USERNAME'}

    else:
        return JsonResponse({
            'message': 'please send the token too!',
        }, encoder=JSONEncoder) 

accountant/users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="fa">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--Font awesome icons -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sahel-font@3.4.0/dist/font-face.min.css">
  <link rel="stylesheet" href="{% static '/home/style.css' %}">
    <title>{% block title %} {% endblock %} </title>
</head>
<body>
  <div class="container p-3 my-3">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-md navbar-light " style="background-color: #f0f5f5">
          <a href="/" class="navbar-brand">sandooqche</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <p class="lead">
              <hr>
              {% if user.is_authenticated %}
              <a class="btn btn-lg" href="{% url 'logout' %}" role="button">خروج</a>
              {% else %}
                  <a class="btn btn-lg" href="{% url 'login' %}" role="button">ورود</a>
              {% endif %}
          </p>
        </nav>
        <!--Any flash messages pop up in any page because this is the base template-->
        {% if messages %}
          <div class="alert alert-dismissible" role="alert">
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- A plugin for password show/hide  -->
    <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>

</body>
</html>

accountant/users/templates/users/home.html
{% extends "users/base.html" %}
{% block title %} sandooqche {% endblock title%}
{% block content %}
    <div class="jumbotron">
        <header>
            <h1 class="display-4">صندوقچه</h1>
            <hr>
        </header>
        <div class="income-expense-container">
            <div>
                {% if expenses %}
                    <h3>هزینه‌های شما</h3>
                    <div class="expenses-container">
                        {% for expense in expenses %}
                            <div class="expense-item">
                                <h5>دلیل خرج: {{ expense.text }}</h4>
                                <h6>میزان خرج (به تومان): {{ expense.amount }}</h5>
                                <h6>تاریخ خرج: {{ expense.jalalitime }}</h5>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div>
                {% if incomes %}
                    <h3>درآمدهای شما</h3>
                    <div class="incomes-container">
                        {% for income in incomes %}
                            <div class="expense-item">
                                <h5>دلیل درآمد: {{ income.text }} </h4>
                                <h6>میزان درآمد (به تومان): {{ income.amount }}</h5>
                                <h6>تاریخ درآمد: {{ income.jalalitime }}</h5>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="btn1">
            <p class="lead">
                <hr>
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button class="btn btn-primary btn-lg" type="submit">خروج</button>
                    </form>
                {% else %}
                    <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">ورود</a>
                {% endif %}
            </p>
        </div>
    </div>

{% endblock content %}

accountant/users/templates/users/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'login/images/icons/favicon.ico' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/rtl.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/size.css' %}">
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!--Font awesome icons -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">


	<link rel="stylesheet" href="{% static 'register/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'register/css/size.css' %}">
	<link rel="stylesheet" href="{% static 'register/css/background.css' %}">
	<link rel="stylesheet" href="{% static 'register/css/message.css' %}">
	<link rel="stylesheet" href="{% static 'register/css/message2.css' %}">
	<link rel="stylesheet" href="{% static 'register/css/position.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		{% if form.non_field_errors %}
			<div class="errors">
				{% for error in form.non_field_errors %}
					<span>{{error}}</span>
				{% endfor %}
			</div>
		{% endif %}
		<div class="loginhere myfont"></div>
			{% if messages %}
				<ul class="messages">
					{% for message in messages %}
						<li {% if messages.tags == 'success' %} class="success success-msg" {% else %} class="success-msg" {% endif %}>
							{{ message }}
						</li>
					{% endfor %}
				</ul>
			{% endif %}
		</div>
		<div class="container-login100">
			<div class="wrap-login100 main">

				<form class="login100-form validate-form" method="post">
					{% csrf_token %}
					<span class="login100-form-title p-b-26 myfont">
						صفحه ورود
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is: a@b.c">
						{{ form.username|add_class:"input100" }}
						{% if form.username_errors %}
							<div class="errors">
								{% for error in form.username_errors %}
									<span>{{error}}</span>
								{% endfor %}
							</div>
						{% endif %}		
						<span class="focus-input100" data-placeholder="نام کاربری"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye "></i>
						</span>
						{{ form.password|add_class:"input100"}}
						{% if form.password_errors %}
							<div class="errors">
								{% for error in form.username_errors %}
									<span>{{error}}</span>
								{% endfor %}
							</div>
						{% endif %}		
						<span class="focus-input100" data-placeholder="گذرواژه"></span>
					</div>
					<div class="wrap-input100">
						{{ form.captcha }}
					</div>
					<div class="form-row">
						<div class="col-md-10 offset-md-1">
							<div class="form-group">
								<!-- Add a Remember me functionality -->
								{{ form.remember_me }}
								<label> مرا به خاطر بسپار </label>
							</div>
						</div>
					</div>
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn myfont">
								ورود
							</button>
						</div>
					</div>
				</form>
				<div class="form-row ">
					<p class="loginhere  myfont">
						آیا حساب کاربری ندارید؟ <a href="{% url 'users:users-register' %}" class="loginhere-link myfont">ایجاد حساب</a>
					</p>
				</div>
			</div>
		</div>
	</div>
	
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'login/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'login/js/main.js' %}"></script>

</body>
</html>

accountant/users/templates/users/logout.html
{% extends "users/base.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
    <div class="jumbotron">
        <div class="card-body">
        <h3 class="card-title">از حساب خارج شدید</h5>
        <p class="card-text" style="font-size: large;">
            ممنون که برای استفاده از سرویس های ما زمان گذاشتید. منتظر شما هستیم 
        </p>
        <br><hr>
        <div style="text-align: left;"><a href="{% url 'login' %}" class="btn btn-primary">ورود دوباره</a></div>
        </div>
    </div>


{% endblock content %}